/**
 * CIE-10 - Clasificación Internacional de Enfermedades, 10a Revisión
 * Diagnósticos más frecuentes en atención primaria en Colombia
 *
 * NOTA: Este archivo contiene ~400 códigos de los más comunes.
 * El catálogo completo tiene ~12,000+ códigos y puede importarse
 * desde el portal de datos abiertos o SISPRO.
 */

export interface Cie10Entry {
  codigo: string;
  nombre: string;
}

export const cie10Data: Cie10Entry[] = [
  // ══════════════════════════════════════════════════════════════
  // Cap I: A00-B99 Enfermedades infecciosas y parasitarias
  // ══════════════════════════════════════════════════════════════
  { codigo: "A00", nombre: "COLERA" },
  { codigo: "A01", nombre: "FIEBRES TIFOIDEA Y PARATIFOIDEA" },
  { codigo: "A02", nombre: "OTRAS INFECCIONES POR SALMONELLA" },
  { codigo: "A04", nombre: "OTRAS INFECCIONES INTESTINALES BACTERIANAS" },
  { codigo: "A05", nombre: "OTRAS INTOXICACIONES ALIMENTARIAS BACTERIANAS" },
  { codigo: "A06", nombre: "AMEBIASIS" },
  { codigo: "A08", nombre: "INFECCIONES INTESTINALES DEBIDAS A VIRUS" },
  { codigo: "A09", nombre: "DIARREA Y GASTROENTERITIS DE PRESUNTO ORIGEN INFECCIOSO" },
  { codigo: "A15", nombre: "TUBERCULOSIS RESPIRATORIA CONFIRMADA BACTERIOLOGICA E HISTOLOGICAMENTE" },
  { codigo: "A16", nombre: "TUBERCULOSIS RESPIRATORIA NO CONFIRMADA BACTERIOLOGICA O HISTOLOGICAMENTE" },
  { codigo: "A37", nombre: "TOS FERINA" },
  { codigo: "A38", nombre: "ESCARLATINA" },
  { codigo: "A49", nombre: "INFECCION BACTERIANA EN SITIO NO ESPECIFICADO" },
  { codigo: "A50", nombre: "SIFILIS CONGENITA" },
  { codigo: "A51", nombre: "SIFILIS PRECOZ" },
  { codigo: "A53", nombre: "OTRAS SIFILIS Y LAS NO ESPECIFICADAS" },
  { codigo: "A54", nombre: "INFECCION GONOCOCICA" },
  { codigo: "A56", nombre: "OTRAS ENFERMEDADES DE TRANSMISION SEXUAL POR CLAMIDIA" },
  { codigo: "A60", nombre: "INFECCION ANOGENITAL DEBIDA A VIRUS DEL HERPES" },
  { codigo: "A63", nombre: "OTRAS ENFERMEDADES DE TRANSMISION PREDOMINANTEMENTE SEXUAL" },
  { codigo: "A64", nombre: "ENFERMEDAD DE TRANSMISION SEXUAL NO ESPECIFICADA" },
  { codigo: "A69", nombre: "OTRAS INFECCIONES POR ESPIROQUETAS" },
  { codigo: "A86", nombre: "ENCEFALITIS VIRAL NO ESPECIFICADA" },
  { codigo: "A90", nombre: "FIEBRE DEL DENGUE" },
  { codigo: "A91", nombre: "FIEBRE DEL DENGUE HEMORRAGICO" },
  { codigo: "B00", nombre: "INFECCIONES HERPETICAS" },
  { codigo: "B01", nombre: "VARICELA" },
  { codigo: "B02", nombre: "HERPES ZOSTER" },
  { codigo: "B05", nombre: "SARAMPION" },
  { codigo: "B06", nombre: "RUBEOLA" },
  { codigo: "B07", nombre: "VERRUGAS VIRICAS" },
  { codigo: "B15", nombre: "HEPATITIS AGUDA TIPO A" },
  { codigo: "B16", nombre: "HEPATITIS AGUDA TIPO B" },
  { codigo: "B17", nombre: "OTRAS HEPATITIS VIRALES AGUDAS" },
  { codigo: "B18", nombre: "HEPATITIS VIRAL CRONICA" },
  { codigo: "B20", nombre: "ENFERMEDAD POR VIRUS DE LA INMUNODEFICIENCIA HUMANA (VIH)" },
  { codigo: "B35", nombre: "DERMATOFITOSIS" },
  { codigo: "B36", nombre: "OTRAS MICOSIS SUPERFICIALES" },
  { codigo: "B37", nombre: "CANDIDIASIS" },
  { codigo: "B65", nombre: "ESQUISTOSOMIASIS" },
  { codigo: "B77", nombre: "ASCARIASIS" },
  { codigo: "B80", nombre: "ENTEROBIASIS" },
  { codigo: "B82", nombre: "PARASITOSIS INTESTINAL SIN OTRA ESPECIFICACION" },
  { codigo: "B86", nombre: "ESCABIOSIS" },
  // ══════════════════════════════════════════════════════════════
  // Cap II: C00-D48 Neoplasias
  // ══════════════════════════════════════════════════════════════
  { codigo: "C16", nombre: "TUMOR MALIGNO DEL ESTOMAGO" },
  { codigo: "C18", nombre: "TUMOR MALIGNO DEL COLON" },
  { codigo: "C34", nombre: "TUMOR MALIGNO DE LOS BRONQUIOS Y DEL PULMON" },
  { codigo: "C43", nombre: "MELANOMA MALIGNO DE LA PIEL" },
  { codigo: "C44", nombre: "OTROS TUMORES MALIGNOS DE LA PIEL" },
  { codigo: "C50", nombre: "TUMOR MALIGNO DE LA MAMA" },
  { codigo: "C53", nombre: "TUMOR MALIGNO DEL CUELLO DEL UTERO" },
  { codigo: "C54", nombre: "TUMOR MALIGNO DEL CUERPO DEL UTERO" },
  { codigo: "C56", nombre: "TUMOR MALIGNO DEL OVARIO" },
  { codigo: "C61", nombre: "TUMOR MALIGNO DE LA PROSTATA" },
  { codigo: "C73", nombre: "TUMOR MALIGNO DE LA GLANDULA TIROIDES" },
  { codigo: "D17", nombre: "TUMOR BENIGNO LIPOMATOSO" },
  { codigo: "D22", nombre: "NEVO MELANOCITICO" },
  { codigo: "D25", nombre: "LEIOMIOMA DEL UTERO" },
  { codigo: "D50", nombre: "ANEMIA POR DEFICIENCIA DE HIERRO" },
  // ══════════════════════════════════════════════════════════════
  // Cap IV: E00-E90 Enfermedades endocrinas y metabólicas
  // ══════════════════════════════════════════════════════════════
  { codigo: "E03", nombre: "OTROS HIPOTIROIDISMOS" },
  { codigo: "E04", nombre: "OTROS BOCIOS NO TOXICOS" },
  { codigo: "E05", nombre: "TIROTOXICOSIS (HIPERTIROIDISMO)" },
  { codigo: "E06", nombre: "TIROIDITIS" },
  { codigo: "E10", nombre: "DIABETES MELLITUS INSULINODEPENDIENTE" },
  { codigo: "E11", nombre: "DIABETES MELLITUS NO INSULINODEPENDIENTE" },
  { codigo: "E13", nombre: "OTROS TIPOS ESPECIFICADOS DE DIABETES MELLITUS" },
  { codigo: "E14", nombre: "DIABETES MELLITUS NO ESPECIFICADA" },
  { codigo: "E40", nombre: "KWASHIORKOR" },
  { codigo: "E43", nombre: "DESNUTRICION PROTEICOCALORICA SEVERA NO ESPECIFICADA" },
  { codigo: "E44", nombre: "DESNUTRICION PROTEICOCALORICA DE GRADO MODERADO Y LEVE" },
  { codigo: "E46", nombre: "DESNUTRICION PROTEICOCALORICA NO ESPECIFICADA" },
  { codigo: "E55", nombre: "DEFICIENCIA DE VITAMINA D" },
  { codigo: "E66", nombre: "OBESIDAD" },
  { codigo: "E78", nombre: "TRASTORNOS DEL METABOLISMO DE LAS LIPOPROTEINAS Y OTRAS LIPIDEMIAS" },
  // ══════════════════════════════════════════════════════════════
  // Cap V: F00-F99 Trastornos mentales
  // ══════════════════════════════════════════════════════════════
  { codigo: "F10", nombre: "TRASTORNOS MENTALES POR USO DE ALCOHOL" },
  { codigo: "F11", nombre: "TRASTORNOS MENTALES POR USO DE OPIOIDES" },
  { codigo: "F12", nombre: "TRASTORNOS MENTALES POR USO DE CANNABINOIDES" },
  { codigo: "F14", nombre: "TRASTORNOS MENTALES POR USO DE COCAINA" },
  { codigo: "F17", nombre: "TRASTORNOS MENTALES POR USO DE TABACO" },
  { codigo: "F20", nombre: "ESQUIZOFRENIA" },
  { codigo: "F31", nombre: "TRASTORNO AFECTIVO BIPOLAR" },
  { codigo: "F32", nombre: "EPISODIO DEPRESIVO" },
  { codigo: "F33", nombre: "TRASTORNO DEPRESIVO RECURRENTE" },
  { codigo: "F40", nombre: "TRASTORNOS DE ANSIEDAD FOBICA" },
  { codigo: "F41", nombre: "OTROS TRASTORNOS DE ANSIEDAD" },
  { codigo: "F43", nombre: "REACCIONES A ESTRES GRAVE Y TRASTORNOS DE ADAPTACION" },
  { codigo: "F45", nombre: "TRASTORNOS SOMATOMORFOS" },
  { codigo: "F48", nombre: "OTROS TRASTORNOS NEUROTICOS" },
  { codigo: "F51", nombre: "TRASTORNOS NO ORGANICOS DEL SUENO" },
  { codigo: "F90", nombre: "TRASTORNOS HIPERCINETICOS" },
  // ══════════════════════════════════════════════════════════════
  // Cap VI: G00-G99 Enfermedades del sistema nervioso
  // ══════════════════════════════════════════════════════════════
  { codigo: "G40", nombre: "EPILEPSIA" },
  { codigo: "G43", nombre: "MIGRANA" },
  { codigo: "G44", nombre: "OTROS SINDROMES DE CEFALEA" },
  { codigo: "G47", nombre: "TRASTORNOS DEL SUENO" },
  { codigo: "G50", nombre: "TRASTORNOS DEL NERVIO TRIGEMINO" },
  { codigo: "G51", nombre: "TRASTORNOS DEL NERVIO FACIAL" },
  { codigo: "G56", nombre: "MONONEUROPATIAS DEL MIEMBRO SUPERIOR" },
  // ══════════════════════════════════════════════════════════════
  // Cap VII: H00-H59 Enfermedades del ojo
  // ══════════════════════════════════════════════════════════════
  { codigo: "H00", nombre: "ORZUELO Y CALACIO" },
  { codigo: "H01", nombre: "OTRAS INFLAMACIONES DEL PARPADO" },
  { codigo: "H04", nombre: "TRASTORNOS DEL APARATO LAGRIMAL" },
  { codigo: "H10", nombre: "CONJUNTIVITIS" },
  { codigo: "H11", nombre: "OTROS TRASTORNOS DE LA CONJUNTIVA" },
  { codigo: "H25", nombre: "CATARATA SENIL" },
  { codigo: "H26", nombre: "OTRAS CATARATAS" },
  { codigo: "H40", nombre: "GLAUCOMA" },
  { codigo: "H52", nombre: "TRASTORNOS DE LA REFRACCION Y DE LA ACOMODACION" },
  // ══════════════════════════════════════════════════════════════
  // Cap VIII: H60-H95 Enfermedades del oído
  // ══════════════════════════════════════════════════════════════
  { codigo: "H60", nombre: "OTITIS EXTERNA" },
  { codigo: "H65", nombre: "OTITIS MEDIA NO SUPURATIVA" },
  { codigo: "H66", nombre: "OTITIS MEDIA SUPURATIVA Y LA NO ESPECIFICADA" },
  { codigo: "H81", nombre: "TRASTORNOS DE LA FUNCION VESTIBULAR" },
  { codigo: "H91", nombre: "OTRAS HIPOACUSIAS" },
  // ══════════════════════════════════════════════════════════════
  // Cap IX: I00-I99 Enfermedades del sistema circulatorio
  // ══════════════════════════════════════════════════════════════
  { codigo: "I10", nombre: "HIPERTENSION ESENCIAL (PRIMARIA)" },
  { codigo: "I11", nombre: "ENFERMEDAD CARDIACA HIPERTENSIVA" },
  { codigo: "I15", nombre: "HIPERTENSION SECUNDARIA" },
  { codigo: "I20", nombre: "ANGINA DE PECHO" },
  { codigo: "I21", nombre: "INFARTO AGUDO DEL MIOCARDIO" },
  { codigo: "I25", nombre: "ENFERMEDAD ISQUEMICA CRONICA DEL CORAZON" },
  { codigo: "I42", nombre: "CARDIOMIOPATIA" },
  { codigo: "I44", nombre: "BLOQUEO AURICULOVENTRICULAR Y DE RAMA IZQUIERDA DEL HAZ" },
  { codigo: "I48", nombre: "FIBRILACION Y ALETEO AURICULAR" },
  { codigo: "I49", nombre: "OTRAS ARRITMIAS CARDIACAS" },
  { codigo: "I50", nombre: "INSUFICIENCIA CARDIACA" },
  { codigo: "I63", nombre: "INFARTO CEREBRAL" },
  { codigo: "I64", nombre: "ACCIDENTE VASCULAR ENCEFALICO AGUDO NO ESPECIFICADO" },
  { codigo: "I67", nombre: "OTRAS ENFERMEDADES CEREBROVASCULARES" },
  { codigo: "I70", nombre: "ATEROSCLEROSIS" },
  { codigo: "I73", nombre: "OTRAS ENFERMEDADES VASCULARES PERIFERICAS" },
  { codigo: "I80", nombre: "FLEBITIS Y TROMBOFLEBITIS" },
  { codigo: "I83", nombre: "VENAS VARICOSAS DE LOS MIEMBROS INFERIORES" },
  { codigo: "I84", nombre: "HEMORROIDES" },
  // ══════════════════════════════════════════════════════════════
  // Cap X: J00-J99 Enfermedades del sistema respiratorio
  // ══════════════════════════════════════════════════════════════
  { codigo: "J00", nombre: "RINOFARINGITIS AGUDA (RESFRIADO COMUN)" },
  { codigo: "J01", nombre: "SINUSITIS AGUDA" },
  { codigo: "J02", nombre: "FARINGITIS AGUDA" },
  { codigo: "J03", nombre: "AMIGDALITIS AGUDA" },
  { codigo: "J04", nombre: "LARINGITIS Y TRAQUEITIS AGUDAS" },
  { codigo: "J06", nombre: "INFECCIONES AGUDAS DE LAS VIAS RESPIRATORIAS SUPERIORES" },
  { codigo: "J10", nombre: "INFLUENZA DEBIDA A VIRUS DE LA INFLUENZA IDENTIFICADO" },
  { codigo: "J11", nombre: "INFLUENZA DEBIDA A VIRUS NO IDENTIFICADO" },
  { codigo: "J12", nombre: "NEUMONIA VIRAL NO CLASIFICADA EN OTRA PARTE" },
  { codigo: "J13", nombre: "NEUMONIA DEBIDA A STREPTOCOCCUS PNEUMONIAE" },
  { codigo: "J15", nombre: "NEUMONIA BACTERIANA NO CLASIFICADA EN OTRA PARTE" },
  { codigo: "J18", nombre: "NEUMONIA ORGANISMO NO ESPECIFICADO" },
  { codigo: "J20", nombre: "BRONQUITIS AGUDA" },
  { codigo: "J21", nombre: "BRONQUIOLITIS AGUDA" },
  { codigo: "J22", nombre: "INFECCION AGUDA NO ESPECIFICADA DE LAS VIAS RESPIRATORIAS INFERIORES" },
  { codigo: "J30", nombre: "RINITIS ALERGICA Y VASOMOTORA" },
  { codigo: "J31", nombre: "RINITIS, NASOFARINGITIS Y FARINGITIS CRONICAS" },
  { codigo: "J32", nombre: "SINUSITIS CRONICA" },
  { codigo: "J34", nombre: "OTROS TRASTORNOS DE LA NARIZ Y DE LOS SENOS PARANASALES" },
  { codigo: "J35", nombre: "ENFERMEDADES CRONICAS DE LAS AMIGDALAS Y DE LAS ADENOIDES" },
  { codigo: "J40", nombre: "BRONQUITIS NO ESPECIFICADA COMO AGUDA O CRONICA" },
  { codigo: "J42", nombre: "BRONQUITIS CRONICA NO ESPECIFICADA" },
  { codigo: "J44", nombre: "OTRAS ENFERMEDADES PULMONARES OBSTRUCTIVAS CRONICAS" },
  { codigo: "J45", nombre: "ASMA" },
  { codigo: "J46", nombre: "ESTADO ASMATICO" },
  // ══════════════════════════════════════════════════════════════
  // Cap XI: K00-K93 Enfermedades del aparato digestivo
  // ══════════════════════════════════════════════════════════════
  { codigo: "K00", nombre: "TRASTORNOS DEL DESARROLLO Y DE LA ERUPCION DE LOS DIENTES" },
  { codigo: "K01", nombre: "DIENTES INCLUIDOS E IMPACTADOS" },
  { codigo: "K02", nombre: "CARIES DENTAL" },
  { codigo: "K03", nombre: "OTRAS ENFERMEDADES DE LOS TEJIDOS DUROS DE LOS DIENTES" },
  { codigo: "K04", nombre: "ENFERMEDADES DE LA PULPA Y DE LOS TEJIDOS PERIAPICALES" },
  { codigo: "K05", nombre: "GINGIVITIS Y ENFERMEDADES PERIODONTALES" },
  { codigo: "K08", nombre: "OTROS TRASTORNOS DE LOS DIENTES Y DE SUS ESTRUCTURAS DE SOSTEN" },
  { codigo: "K21", nombre: "ENFERMEDAD DEL REFLUJO GASTROESOFAGICO" },
  { codigo: "K25", nombre: "ULCERA GASTRICA" },
  { codigo: "K26", nombre: "ULCERA DUODENAL" },
  { codigo: "K27", nombre: "ULCERA PEPTICA DE SITIO NO ESPECIFICADO" },
  { codigo: "K29", nombre: "GASTRITIS Y DUODENITIS" },
  { codigo: "K30", nombre: "DISPEPSIA" },
  { codigo: "K35", nombre: "APENDICITIS AGUDA" },
  { codigo: "K37", nombre: "APENDICITIS NO ESPECIFICADA" },
  { codigo: "K40", nombre: "HERNIA INGUINAL" },
  { codigo: "K42", nombre: "HERNIA UMBILICAL" },
  { codigo: "K52", nombre: "OTRAS GASTROENTERITIS Y COLITIS NO INFECCIOSAS" },
  { codigo: "K56", nombre: "ILEO PARALITICO Y OBSTRUCCION INTESTINAL SIN HERNIA" },
  { codigo: "K58", nombre: "SINDROME DE INTESTINO IRRITABLE" },
  { codigo: "K59", nombre: "OTROS TRASTORNOS FUNCIONALES DEL INTESTINO" },
  { codigo: "K60", nombre: "FISURA Y FISTULA DE LAS REGIONES ANAL Y RECTAL" },
  { codigo: "K70", nombre: "ENFERMEDAD ALCOHOLICA DEL HIGADO" },
  { codigo: "K74", nombre: "FIBROSIS Y CIRROSIS DEL HIGADO" },
  { codigo: "K76", nombre: "OTRAS ENFERMEDADES DEL HIGADO" },
  { codigo: "K80", nombre: "COLELITIASIS" },
  { codigo: "K81", nombre: "COLECISTITIS" },
  { codigo: "K85", nombre: "PANCREATITIS AGUDA" },
  // ══════════════════════════════════════════════════════════════
  // Cap XII: L00-L99 Enfermedades de la piel
  // ══════════════════════════════════════════════════════════════
  { codigo: "L01", nombre: "IMPETIGO" },
  { codigo: "L02", nombre: "ABSCESO CUTANEO, FURUNCULO Y CARBUNCO" },
  { codigo: "L03", nombre: "CELULITIS" },
  { codigo: "L08", nombre: "OTRAS INFECCIONES LOCALES DE LA PIEL Y DEL TEJIDO SUBCUTANEO" },
  { codigo: "L20", nombre: "DERMATITIS ATOPICA" },
  { codigo: "L21", nombre: "DERMATITIS SEBORREICA" },
  { codigo: "L23", nombre: "DERMATITIS ALERGICA DE CONTACTO" },
  { codigo: "L24", nombre: "DERMATITIS DE CONTACTO POR IRRITANTES" },
  { codigo: "L25", nombre: "DERMATITIS DE CONTACTO NO ESPECIFICADA" },
  { codigo: "L27", nombre: "DERMATITIS DEBIDA A SUSTANCIAS INGERIDAS" },
  { codigo: "L29", nombre: "PRURITO" },
  { codigo: "L30", nombre: "OTRAS DERMATITIS" },
  { codigo: "L40", nombre: "PSORIASIS" },
  { codigo: "L42", nombre: "PITIRIASIS ROSADA" },
  { codigo: "L43", nombre: "LIQUEN PLANO" },
  { codigo: "L50", nombre: "URTICARIA" },
  { codigo: "L60", nombre: "TRASTORNOS DE LAS UNAS" },
  { codigo: "L65", nombre: "OTRA PERDIDA NO CICATRICIAL DEL PELO" },
  { codigo: "L70", nombre: "ACNE" },
  { codigo: "L72", nombre: "QUISTE FOLICULAR DE LA PIEL Y DEL TEJIDO SUBCUTANEO" },
  { codigo: "L73", nombre: "OTROS TRASTORNOS FOLICULARES" },
  { codigo: "L82", nombre: "QUERATOSIS SEBORREICA" },
  // ══════════════════════════════════════════════════════════════
  // Cap XIII: M00-M99 Enfermedades del sistema osteomuscular
  // ══════════════════════════════════════════════════════════════
  { codigo: "M06", nombre: "OTRAS ARTRITIS REUMATOIDES" },
  { codigo: "M10", nombre: "GOTA" },
  { codigo: "M13", nombre: "OTRAS ARTRITIS" },
  { codigo: "M15", nombre: "POLIARTROSIS" },
  { codigo: "M16", nombre: "COXARTROSIS (ARTROSIS DE LA CADERA)" },
  { codigo: "M17", nombre: "GONARTROSIS (ARTROSIS DE LA RODILLA)" },
  { codigo: "M19", nombre: "OTRAS ARTROSIS" },
  { codigo: "M23", nombre: "TRASTORNO INTERNO DE LA RODILLA" },
  { codigo: "M25", nombre: "OTROS TRASTORNOS ARTICULARES" },
  { codigo: "M41", nombre: "ESCOLIOSIS" },
  { codigo: "M42", nombre: "OSTEOCONDROSIS DE LA COLUMNA VERTEBRAL" },
  { codigo: "M43", nombre: "OTRAS DORSOPATIAS DEFORMANTES" },
  { codigo: "M47", nombre: "ESPONDILOSIS" },
  { codigo: "M50", nombre: "TRASTORNOS DE DISCO CERVICAL" },
  { codigo: "M51", nombre: "OTROS TRASTORNOS DE LOS DISCOS INTERVERTEBRALES" },
  { codigo: "M54", nombre: "DORSALGIA" },
  { codigo: "M62", nombre: "OTROS TRASTORNOS DE LOS MUSCULOS" },
  { codigo: "M65", nombre: "SINOVITIS Y TENOSINOVITIS" },
  { codigo: "M67", nombre: "OTROS TRASTORNOS DE LAS MEMBRANAS SINOVIALES Y DE LOS TENDONES" },
  { codigo: "M70", nombre: "TRASTORNOS DE LOS TEJIDOS BLANDOS RELACIONADOS CON EL USO" },
  { codigo: "M72", nombre: "TRASTORNOS FIBROBLASTICOS" },
  { codigo: "M75", nombre: "LESIONES DEL HOMBRO" },
  { codigo: "M77", nombre: "OTRAS ENTESOPATIAS" },
  { codigo: "M79", nombre: "OTROS TRASTORNOS DE LOS TEJIDOS BLANDOS" },
  { codigo: "M80", nombre: "OSTEOPOROSIS CON FRACTURA PATOLOGICA" },
  { codigo: "M81", nombre: "OSTEOPOROSIS SIN FRACTURA PATOLOGICA" },
  // ══════════════════════════════════════════════════════════════
  // Cap XIV: N00-N99 Enfermedades del aparato genitourinario
  // ══════════════════════════════════════════════════════════════
  { codigo: "N10", nombre: "NEFRITIS TUBULOINTERSTICIAL AGUDA" },
  { codigo: "N11", nombre: "NEFRITIS TUBULOINTERSTICIAL CRONICA" },
  { codigo: "N17", nombre: "INSUFICIENCIA RENAL AGUDA" },
  { codigo: "N18", nombre: "INSUFICIENCIA RENAL CRONICA" },
  { codigo: "N20", nombre: "CALCULO DEL RINON Y DEL URETER" },
  { codigo: "N21", nombre: "CALCULO DE LAS VIAS URINARIAS INFERIORES" },
  { codigo: "N23", nombre: "COLICO RENAL NO ESPECIFICADO" },
  { codigo: "N30", nombre: "CISTITIS" },
  { codigo: "N34", nombre: "URETRITIS Y SINDROME URETRAL" },
  { codigo: "N39", nombre: "OTROS TRASTORNOS DEL SISTEMA URINARIO" },
  { codigo: "N40", nombre: "HIPERPLASIA DE LA PROSTATA" },
  { codigo: "N41", nombre: "ENFERMEDADES INFLAMATORIAS DE LA PROSTATA" },
  { codigo: "N43", nombre: "HIDROCELE Y ESPERMATOCELE" },
  { codigo: "N44", nombre: "TORSION DEL TESTICULO" },
  { codigo: "N47", nombre: "TRASTORNOS DEL PREPUCIO" },
  { codigo: "N60", nombre: "DISPLASIA MAMARIA BENIGNA" },
  { codigo: "N63", nombre: "MASA NO ESPECIFICADA EN LA MAMA" },
  { codigo: "N70", nombre: "SALPINGITIS Y OOFORITIS" },
  { codigo: "N72", nombre: "ENFERMEDAD INFLAMATORIA DEL CUELLO UTERINO" },
  { codigo: "N73", nombre: "OTRAS ENFERMEDADES INFLAMATORIAS PELVICAS FEMENINAS" },
  { codigo: "N76", nombre: "OTRAS ENFERMEDADES INFLAMATORIAS DE LA VAGINA Y DE LA VULVA" },
  { codigo: "N80", nombre: "ENDOMETRIOSIS" },
  { codigo: "N83", nombre: "TRASTORNOS NO INFLAMATORIOS DEL OVARIO, TROMPA DE FALOPIO Y LIGAMENTO ANCHO" },
  { codigo: "N84", nombre: "POLIPO DEL TRACTO GENITAL FEMENINO" },
  { codigo: "N85", nombre: "OTROS TRASTORNOS NO INFLAMATORIOS DEL UTERO" },
  { codigo: "N87", nombre: "DISPLASIA DEL CUELLO UTERINO" },
  { codigo: "N91", nombre: "MENSTRUACION AUSENTE ESCASA Y RARA" },
  { codigo: "N92", nombre: "MENSTRUACION EXCESIVA FRECUENTE E IRREGULAR" },
  { codigo: "N93", nombre: "OTRAS HEMORRAGIAS UTERINAS O VAGINALES ANORMALES" },
  { codigo: "N94", nombre: "DOLOR Y OTRAS AFECCIONES ASOCIADAS CON LOS ORGANOS GENITALES FEMENINOS" },
  { codigo: "N95", nombre: "TRASTORNOS MENOPAUSICOS Y OTROS TRASTORNOS PERIMENOPAUSICOS" },
  // ══════════════════════════════════════════════════════════════
  // Cap XV: O00-O99 Embarazo, parto y puerperio
  // ══════════════════════════════════════════════════════════════
  { codigo: "O00", nombre: "EMBARAZO ECTOPICO" },
  { codigo: "O03", nombre: "ABORTO ESPONTANEO" },
  { codigo: "O06", nombre: "ABORTO NO ESPECIFICADO" },
  { codigo: "O10", nombre: "HIPERTENSION PREEXISTENTE QUE COMPLICA EL EMBARAZO" },
  { codigo: "O13", nombre: "HIPERTENSION GESTACIONAL SIN PROTEINURIA SIGNIFICATIVA" },
  { codigo: "O14", nombre: "HIPERTENSION GESTACIONAL CON PROTEINURIA SIGNIFICATIVA" },
  { codigo: "O20", nombre: "HEMORRAGIA PRECOZ DEL EMBARAZO" },
  { codigo: "O21", nombre: "VOMITOS EXCESIVOS EN EL EMBARAZO" },
  { codigo: "O23", nombre: "INFECCIONES DE LAS VIAS GENITOURINARIAS EN EL EMBARAZO" },
  { codigo: "O24", nombre: "DIABETES MELLITUS EN EL EMBARAZO" },
  { codigo: "O26", nombre: "ATENCION A LA MADRE POR OTRAS COMPLICACIONES RELACIONADAS CON EL EMBARAZO" },
  { codigo: "O34", nombre: "ATENCION MATERNA POR ANORMALIDADES CONOCIDAS O PRESUNTAS DE LOS ORGANOS PELVICOS" },
  { codigo: "O36", nombre: "ATENCION MATERNA POR OTROS PROBLEMAS FETALES CONOCIDOS O PRESUNTOS" },
  { codigo: "O42", nombre: "RUPTURA PREMATURA DE LAS MEMBRANAS" },
  { codigo: "O47", nombre: "FALSO TRABAJO DE PARTO" },
  { codigo: "O60", nombre: "PARTO PRETERMINO" },
  { codigo: "O80", nombre: "PARTO UNICO ESPONTANEO" },
  { codigo: "O82", nombre: "PARTO UNICO POR CESAREA" },
  // ══════════════════════════════════════════════════════════════
  // Cap XVI: P00-P96 Afecciones perinatales
  // ══════════════════════════════════════════════════════════════
  { codigo: "P07", nombre: "TRASTORNOS RELACIONADOS CON DURACION CORTA DE LA GESTACION Y CON BAJO PESO AL NACER" },
  { codigo: "P22", nombre: "DIFICULTAD RESPIRATORIA DEL RECIEN NACIDO" },
  { codigo: "P36", nombre: "SEPSIS BACTERIANA DEL RECIEN NACIDO" },
  { codigo: "P59", nombre: "ICTERICIA NEONATAL POR OTRAS CAUSAS Y POR LAS NO ESPECIFICADAS" },
  // ══════════════════════════════════════════════════════════════
  // Cap XVIII: R00-R99 Síntomas, signos y hallazgos anormales
  // ══════════════════════════════════════════════════════════════
  { codigo: "R00", nombre: "ANORMALIDADES DEL LATIDO CARDIACO" },
  { codigo: "R01", nombre: "SOPLOS Y OTROS SONIDOS CARDIACOS" },
  { codigo: "R03", nombre: "LECTURA ANORMAL DE LA PRESION ARTERIAL SIN DIAGNOSTICO" },
  { codigo: "R04", nombre: "HEMORRAGIA DE LAS VIAS RESPIRATORIAS" },
  { codigo: "R05", nombre: "TOS" },
  { codigo: "R06", nombre: "ANORMALIDADES DE LA RESPIRACION" },
  { codigo: "R07", nombre: "DOLOR EN LA GARGANTA Y EN EL PECHO" },
  { codigo: "R10", nombre: "DOLOR ABDOMINAL Y PELVICO" },
  { codigo: "R11", nombre: "NAUSEA Y VOMITO" },
  { codigo: "R21", nombre: "SALPULLIDO Y OTRAS ERUPCIONES CUTANEAS NO ESPECIFICADAS" },
  { codigo: "R30", nombre: "DOLOR ASOCIADO CON LA MICCION" },
  { codigo: "R42", nombre: "MAREO Y DESVANECIMIENTO" },
  { codigo: "R50", nombre: "FIEBRE DE ORIGEN DESCONOCIDO" },
  { codigo: "R51", nombre: "CEFALEA" },
  { codigo: "R52", nombre: "DOLOR NO CLASIFICADO EN OTRA PARTE" },
  { codigo: "R53", nombre: "MALESTAR Y FATIGA" },
  { codigo: "R55", nombre: "SINCOPE Y COLAPSO" },
  { codigo: "R56", nombre: "CONVULSIONES NO CLASIFICADAS EN OTRA PARTE" },
  { codigo: "R73", nombre: "NIVEL ELEVADO DE GLUCOSA EN SANGRE" },
  // ══════════════════════════════════════════════════════════════
  // Cap XIX: S00-T98 Traumatismos y envenenamiento
  // ══════════════════════════════════════════════════════════════
  { codigo: "S00", nombre: "TRAUMATISMO SUPERFICIAL DE LA CABEZA" },
  { codigo: "S01", nombre: "HERIDA DE LA CABEZA" },
  { codigo: "S06", nombre: "TRAUMATISMO INTRACRANEAL" },
  { codigo: "S09", nombre: "OTROS TRAUMATISMOS Y LOS NO ESPECIFICADOS DE LA CABEZA" },
  { codigo: "S13", nombre: "LUXACION, ESGUINCE Y TORCEDURA DE ARTICULACIONES Y LIGAMENTOS DEL CUELLO" },
  { codigo: "S22", nombre: "FRACTURA DE COSTILLA(S) ESTERNON Y COLUMNA TORACICA" },
  { codigo: "S32", nombre: "FRACTURA DE COLUMNA LUMBAR Y DE LA PELVIS" },
  { codigo: "S42", nombre: "FRACTURA DEL HOMBRO Y DEL BRAZO" },
  { codigo: "S52", nombre: "FRACTURA DEL ANTEBRAZO" },
  { codigo: "S62", nombre: "FRACTURA A NIVEL DE LA MUNECA Y DE LA MANO" },
  { codigo: "S72", nombre: "FRACTURA DEL FEMUR" },
  { codigo: "S82", nombre: "FRACTURA DE LA PIERNA INCLUSIVE EL TOBILLO" },
  { codigo: "S83", nombre: "LUXACION ESGUINCE Y TORCEDURA DE ARTICULACIONES Y LIGAMENTOS DE LA RODILLA" },
  { codigo: "S92", nombre: "FRACTURA DEL PIE EXCEPTO DEL TOBILLO" },
  { codigo: "S93", nombre: "LUXACION ESGUINCE Y TORCEDURA DE ARTICULACIONES Y LIGAMENTOS DEL TOBILLO Y DEL PIE" },
  { codigo: "T14", nombre: "TRAUMATISMO DE REGION DEL CUERPO NO ESPECIFICADA" },
  { codigo: "T78", nombre: "EFECTOS ADVERSOS NO CLASIFICADOS EN OTRA PARTE" },
  // ══════════════════════════════════════════════════════════════
  // Cap XXI: Z00-Z99 Factores que influyen en el estado de salud
  // ══════════════════════════════════════════════════════════════
  { codigo: "Z00", nombre: "EXAMEN GENERAL E INVESTIGACION DE PERSONAS SIN QUEJAS O SIN DIAGNOSTICO INFORMADO" },
  { codigo: "Z01", nombre: "OTROS EXAMENES ESPECIALES E INVESTIGACIONES EN PERSONAS SIN QUEJAS" },
  { codigo: "Z02", nombre: "EXAMEN Y CONTACTO CON FINES ADMINISTRATIVOS" },
  { codigo: "Z03", nombre: "OBSERVACION Y EVALUACION MEDICAS POR SOSPECHA DE ENFERMEDADES Y AFECCIONES" },
  { codigo: "Z09", nombre: "EXAMEN DE SEGUIMIENTO DESPUES DE TRATAMIENTO POR OTRAS AFECCIONES" },
  { codigo: "Z12", nombre: "EXAMEN DE PESQUISA ESPECIAL PARA TUMOR" },
  { codigo: "Z23", nombre: "NECESIDAD DE INMUNIZACION CONTRA COMBINACIONES DE ENFERMEDADES INFECCIOSAS" },
  { codigo: "Z30", nombre: "ATENCION PARA LA ANTICONCEPCION" },
  { codigo: "Z32", nombre: "EXAMEN Y PRUEBA DEL EMBARAZO" },
  { codigo: "Z34", nombre: "SUPERVISION DE EMBARAZO NORMAL" },
  { codigo: "Z35", nombre: "SUPERVISION DE EMBARAZO DE ALTO RIESGO" },
  { codigo: "Z36", nombre: "EXAMEN PRENATAL" },
  { codigo: "Z39", nombre: "ATENCION Y EXAMEN DEL POSTPARTO" },
  { codigo: "Z71", nombre: "PERSONAS EN CONTACTO CON LOS SERVICIOS DE SALUD POR OTRAS CONSULTAS Y CONSEJOS MEDICOS" },
  { codigo: "Z76", nombre: "PERSONAS EN CONTACTO CON LOS SERVICIOS DE SALUD EN OTRAS CIRCUNSTANCIAS" },
];
