/**
 * Fetches the complete DIVIPOLA dataset from the Colombian Open Data portal (datos.gov.co).
 * Dataset: "Codigos DANE" - Socrata resource ID: gdxc-w37w
 *
 * Usage:
 *   npx tsx scripts/fetch-divipola.ts
 *
 * This script will:
 * 1. Fetch all municipalities from the Socrata API
 * 2. Derive the departments list from them
 * 3. Write two JSON files: departamentos-dane.json and municipios-dane.json
 */

import { writeFileSync } from "fs";
import { resolve } from "path";

// ---------- Types ----------
interface SocrataRow {
  c_digo_dane_del_departamento?: string;
  departamento?: string;
  c_digo_dane_del_municipio?: string;
  municipio?: string;
  // Alternative column names (the API sometimes uses different casing/names)
  codigo_dane_del_departamento?: string;
  nombre_departamento?: string;
  codigo_dane_del_municipio?: string;
  nombre_municipio?: string;
}

interface Departamento {
  codigo: string;
  nombre: string;
}

interface Municipio {
  codigo: string;
  nombre: string;
  codigo_departamento: string;
}

// ---------- Socrata API endpoints to try ----------
const ENDPOINTS = [
  // Primary: "Codigos DANE" dataset
  "https://www.datos.gov.co/resource/gdxc-w37w.json?$limit=1500",
  // Alternative: DIVIPOLA dataset
  "https://www.datos.gov.co/resource/xdk5-pm3f.json?$limit=1500",
];

async function fetchFromSocrata(): Promise<SocrataRow[]> {
  for (const url of ENDPOINTS) {
    try {
      console.log(`Trying: ${url}`);
      const response = await fetch(url, {
        headers: { Accept: "application/json" },
      });

      if (!response.ok) {
        console.warn(`  HTTP ${response.status} - skipping`);
        continue;
      }

      const data = (await response.json()) as SocrataRow[];
      if (Array.isArray(data) && data.length > 100) {
        console.log(`  Success: ${data.length} rows`);
        return data;
      }
      console.warn(`  Only ${data.length} rows - trying next endpoint`);
    } catch (err) {
      console.warn(`  Error: ${(err as Error).message} - trying next endpoint`);
    }
  }
  throw new Error(
    "Could not fetch DIVIPOLA data from any endpoint. Check your internet connection."
  );
}

function normalizeRows(rows: SocrataRow[]): {
  departamentos: Departamento[];
  municipios: Municipio[];
} {
  const deptMap = new Map<string, string>();
  const municipios: Municipio[] = [];

  for (const row of rows) {
    // Handle different column name variations from the API
    const codDepto =
      row.c_digo_dane_del_departamento ??
      row.codigo_dane_del_departamento ??
      "";
    const nomDepto =
      row.departamento ?? row.nombre_departamento ?? "";
    const codMuni =
      row.c_digo_dane_del_municipio ??
      row.codigo_dane_del_municipio ??
      "";
    const nomMuni = row.municipio ?? row.nombre_municipio ?? "";

    if (!codDepto || !codMuni) continue;

    // Normalize department code to 2 digits
    const deptoCode = codDepto.toString().padStart(2, "0");
    // Normalize municipality code to 5 digits
    const muniCode = codMuni.toString().padStart(5, "0");

    deptMap.set(deptoCode, nomDepto.toUpperCase().trim());

    municipios.push({
      codigo: muniCode,
      nombre: nomMuni.toUpperCase().trim(),
      codigo_departamento: deptoCode,
    });
  }

  // Sort
  const departamentos = Array.from(deptMap.entries())
    .map(([codigo, nombre]) => ({ codigo, nombre }))
    .sort((a, b) => a.codigo.localeCompare(b.codigo));

  municipios.sort((a, b) => a.codigo.localeCompare(b.codigo));

  return { departamentos, municipios };
}

async function main() {
  console.log("Fetching DIVIPOLA data from datos.gov.co...\n");

  const rows = await fetchFromSocrata();
  const { departamentos, municipios } = normalizeRows(rows);

  console.log(`\nParsed ${departamentos.length} departamentos`);
  console.log(`Parsed ${municipios.length} municipios\n`);

  // Write JSON files
  const outDir = resolve(__dirname, "data");

  const deptPath = resolve(outDir, "departamentos-dane.json");
  writeFileSync(deptPath, JSON.stringify(departamentos, null, 2), "utf-8");
  console.log(`Written: ${deptPath}`);

  const muniPath = resolve(outDir, "municipios-dane.json");
  writeFileSync(muniPath, JSON.stringify(municipios, null, 2), "utf-8");
  console.log(`Written: ${muniPath}`);

  // Also generate TypeScript exports for type safety
  const deptTsContent = `/**
 * Departamentos de Colombia - DANE DIVIPOLA
 * Auto-generated by fetch-divipola.ts on ${new Date().toISOString().split("T")[0]}
 * ${departamentos.length} departamentos
 */
export const departamentos: { codigo: string; nombre: string }[] = ${JSON.stringify(departamentos, null, 2)};
`;

  const muniTsContent = `/**
 * Municipios de Colombia - DANE DIVIPOLA
 * Auto-generated by fetch-divipola.ts on ${new Date().toISOString().split("T")[0]}
 * ${municipios.length} municipios
 */
export const municipios: { codigo: string; nombre: string; codigo_departamento: string }[] = ${JSON.stringify(municipios, null, 2)};
`;

  const deptTsPath = resolve(outDir, "departamentos-dane.ts");
  writeFileSync(deptTsPath, deptTsContent, "utf-8");
  console.log(`Written: ${deptTsPath}`);

  const muniTsPath = resolve(outDir, "municipios-dane.ts");
  writeFileSync(muniTsPath, muniTsContent, "utf-8");
  console.log(`Written: ${muniTsPath}`);

  console.log("\nDone! You can now run: npm run db:seed");
}

main().catch((err) => {
  console.error("Fatal error:", err.message);
  process.exit(1);
});
